title: THE GOAT REPO
description: THE GOAT REPOSITORY
owner_name: Zhengji Li
github_username: xinjiav3
github_repo: "testing"
baseurl: "/testing"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
  social links:
    - { platform: github, user_url: "https://github.com/"}
    - { platform: x, user_url: "https://x.com/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@" } 
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
header_pages: